#
# Codecov Docs:
# https://docs.codecov.com/docs
#
# Codecov Reports:
# https://app.codecov.io/gh/chora-io/server
#
coverage:
  precision: 2
  round: down
  range: 70...100
  status:
    project:
      default:
        threshold: 1%
      api:
        paths:
          - "api/"
      db:
        paths:
          - "db/"
      idx:
        paths:
          - "idx/"
    changes: false

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: true
