services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres.Dockerfile
    entrypoint: ["/bin/sh", "-c", "./scripts/postgres_start.sh"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    network_mode: host
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 100

  fuseki:
    image: stain/jena-fuseki:jena4
    environment:
      ADMIN_PASSWORD: fuseki
      FUSEKI_DATASET_1: resources
    network_mode: host
    expose:
      - 3030
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3030 || exit 1"]
      interval: 1s
      timeout: 10s
      retries: 100

  chora:
    build:
      context: .
      dockerfile: docker/chora.Dockerfile
    entrypoint: ["/bin/sh", "-c", "./scripts/chora_start.sh"]
    network_mode: host
    expose:
      - 1317
      - 26657
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:26657 || exit 1"]
      interval: 1s
      timeout: 10s
      retries: 100

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    environment:
      DATABASE_URL: "postgres://postgres:password@localhost:5432/postgres?sslmode=disable"
    entrypoint: [ "/bin/sh", "-c", "go run ./cmd/api" ]
    network_mode: host
    expose:
      - 3000
    depends_on:
      postgres:
        condition: service_healthy

  idx:
    build:
      context: .
      dockerfile: docker/idx.Dockerfile
    environment:
      DATABASE_URL: "postgres://postgres:password@localhost:5432/postgres?sslmode=disable"
    entrypoint: [ "/bin/sh", "-c", "go run ./cmd/idx localhost:9090 chora-local" ]
    network_mode: host
    depends_on:
      postgres:
        condition: service_healthy
      chora:
        condition: service_healthy

  tester:
    build:
      context: .
      dockerfile: docker/tester.Dockerfile
    entrypoint: ["/bin/sh", "-c", "./scripts/tester_start.sh"]
    network_mode: host
    depends_on:
      postgres:
        condition: service_healthy
      chora:
        condition: service_healthy
      idx:
        condition: service_started
