services:
  fuseki:
    image: stain/jena-fuseki:jena4
    expose:
      - 3030
    ports:
      - 3030:3030
    networks:
      - default
    environment:
      - ADMIN_PASSWORD=fuseki
      - FUSEKI_DATASET_1=resources

  postgres:
    image: postgres:15
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 100

  api:
    build:
      context: api
    environment:
      DATABASE_URL: "postgres://postgres:password@postgres:5432/postgres?sslmode=disable"
    entrypoint: [ "/bin/sh", "-c", "go run ./cmd" ]
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy

  idx:
    build:
      context: idx
    environment:
      DATABASE_URL: "postgres://postgres:password@postgres:5432/postgres?sslmode=disable"
    entrypoint: [ "/bin/sh", "-c", "go run ./cmd" ]
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy

networks:
  default:
    driver: bridge
