services:
  postgres:
    image: postgres:15
    user: postgres
    environment:
      POSTGRES_PASSWORD: password
    network_mode: host
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 100

  fuseki:
    image: stain/jena-fuseki:jena4
    environment:
      ADMIN_PASSWORD: fuseki
      FUSEKI_DATASET_1: resources
    network_mode: host
    expose:
      - 3030
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3030 || exit 1"]
      interval: 1s
      timeout: 10s
      retries: 100

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      DATABASE_URL: "postgres://postgres:password@localhost:5432/postgres?sslmode=disable"
    entrypoint: [ "/bin/sh", "-c", "go run ./cmd/api" ]
    network_mode: host
    expose:
      - 3000
    depends_on:
      postgres:
        condition: service_healthy

  idx:
    build:
      context: .
      dockerfile: idx/Dockerfile
    environment:
      DATABASE_URL: "postgres://postgres:password@localhost:5432/postgres?sslmode=disable"
    entrypoint: [ "/bin/sh", "-c", "go run ./cmd/idx localhost:9090 chora-local 1" ]
    network_mode: host
    depends_on:
      postgres:
        condition: service_healthy
