@startuml

package "https://chora.io/coop" {
    frame "Admin Application Workflow" {
      component "Review Application"
      component "List Applications"
    }
    frame "Member Application Workflow" {
      component "New Application"
      component "View Application"
      component "Edit Application"
      component "Cancel Application"
    }
}

@enduml
