// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import ()

// the data table stores linked data
type Datum struct {
	Iri     string
	Context string
	Jsonld  string
}
