// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: reader.sql

package db

import (
	"context"
)

const getContent = `-- name: GetContent :one
SELECT (body)
FROM content
WHERE (id=$1)
`

func (q *Queries) GetContent(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getContent, id)
	var body string
	err := row.Scan(&body)
	return body, err
}
