// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: writer.sql

package db

import (
	"context"
)

const postData = `-- name: PostData :one
INSERT INTO data (canon, context, jsonld)
VALUES ($1, $2, $3)
RETURNING (id)
`

type PostDataParams struct {
	Canon   string
	Context string
	Jsonld  string
}

func (q *Queries) PostData(ctx context.Context, arg PostDataParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, postData, arg.Canon, arg.Context, arg.Jsonld)
	var id int32
	err := row.Scan(&id)
	return id, err
}
