// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: writer.sql

package db

import (
	"context"
)

const postContent = `-- name: PostContent :one
INSERT INTO content (body)
VALUES ($1)
RETURNING (id)
`

func (q *Queries) PostContent(ctx context.Context, body string) (int64, error) {
	row := q.db.QueryRowContext(ctx, postContent, body)
	var id int64
	err := row.Scan(&id)
	return id, err
}
