name: Lint

# **What it does**: Runs go linter when go files have been modified
# and proto linters when proto files have been modified.
#
# **Why we have it**: Ensures all go files and proto files are
# properly formatted according to lint configuration files.
#
# **What does it impact**: Code quality.

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # for technote-space/get-diff-action to get git reference
    strategy:
      matrix:
        module: ["api", "db", "idx"]
    steps:
      - uses: actions/checkout@v4

      # api module

      - uses: technote-space/get-diff-action@v6
        id: git-diff-api
        with:
          PATTERNS: |
            api/**/**.go
            api/go.mod
            api/go.sum
        if: matrix.module == 'api'
      - uses: actions/setup-go@v5
        with:
          go-version-file: api/go.mod
        if: env.GIT_DIFF
      - uses: golangci/golangci-lint-action@v6
        with:
          working-directory: api
        if: steps.git-diff-api.outputs.diff

      # db module

      - uses: technote-space/get-diff-action@v6
        id: git-diff-db
        with:
          PATTERNS: |
            db/**/**.go
            db/go.mod
            db/go.sum
        if: matrix.module == 'db'
      - uses: actions/setup-go@v5
        with:
          go-version-file: db/go.mod
        if: env.GIT_DIFF
      - uses: golangci/golangci-lint-action@v6
        with:
          working-directory: db
        if: steps.git-diff-api.outputs.diff

      # idx module

      - uses: technote-space/get-diff-action@v6
        id: git-diff-idx
        with:
          PATTERNS: |
            idx/**/**.go
            idx/go.mod
            idx/go.sum
        if: matrix.module == 'idx'
      - uses: actions/setup-go@v5
        with:
          go-version-file: idx/go.mod
        if: env.GIT_DIFF
      - uses: golangci/golangci-lint-action@v6
        with:
          working-directory: idx
        if: steps.git-diff-api.outputs.diff
