name: Test

# **What it does**: Runs unit and integration tests when go files
# have been modified and provides code coverage reports.
#
# **Why we have it**: Ensures the application is production ready.
#
# **What does it impact**: Application stability.

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # for technote-space/get-diff-action to get git reference
    strategy:
      matrix:
        module: ["api", "db", "indexer", "monitor", "state"]
    steps:
      - uses: actions/checkout@v3

      # api module

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            api/**/**.go
            api/go.mod
            api/go.sum
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'api/go.mod'
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - run: make test-api
        if: |
          (env.GIT_DIFF && matrix.module == 'api') ||
          github.ref == 'refs/heads/main'
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-api
          path: coverage-api.out
        if: |
          (env.GIT_DIFF && matrix.module == 'api') ||
          github.ref == 'refs/heads/main'

      # db module

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            db/**/**.go
            db/go.mod
            db/go.sum
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'db/go.mod'
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - run: make test-db
        if: |
          (env.GIT_DIFF && matrix.module == 'db') ||
          github.ref == 'refs/heads/main'
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-db
          path: coverage-db.out
        if: |
          (env.GIT_DIFF && matrix.module == 'db') ||
          github.ref == 'refs/heads/main'

      # indexer module

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            indexer/**/**.go
            indexer/go.mod
            indexer/go.sum
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'indexer/go.mod'
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - run: make test-indexer
        if: |
          (env.GIT_DIFF && matrix.module == 'indexer') ||
          github.ref == 'refs/heads/main'
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-indexer
          path: coverage-indexer.out
        if: |
          (env.GIT_DIFF && matrix.module == 'indexer') ||
          github.ref == 'refs/heads/main'

      # monitor module

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            monitor/**/**.go
            monitor/go.mod
            monitor/go.sum
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'monitor/go.mod'
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - run: make test-monitor
        if: |
          (env.GIT_DIFF && matrix.module == 'monitor') ||
          github.ref == 'refs/heads/main'
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-monitor
          path: coverage-monitor.out
        if: |
          (env.GIT_DIFF && matrix.module == 'monitor') ||
          github.ref == 'refs/heads/main'

      # state module

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            state/**/**.go
            state/go.mod
            state/go.sum
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'state/go.mod'
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - run: make test-state
        if: |
          (env.GIT_DIFF && matrix.module == 'state') ||
          github.ref == 'refs/heads/main'
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-state
          path: coverage-state.out
        if: |
          (env.GIT_DIFF && matrix.module == 'state') ||
          github.ref == 'refs/heads/main'

  coverage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # for technote-space/get-diff-action to get git reference
    needs: [unit]
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            **/go.mod
            **/go.sum
      - uses: actions/download-artifact@v3
        with:
          name: coverage-api
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - run: make test-coverage
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - uses: codecov/codecov-action@v3
        with:
          file: coverage.txt
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
