name: Test

# **What it does**: Runs unit and integration tests when go files
# have been modified and provides code coverage reports.
#
# **Why we have it**: Ensures the application is production ready.
#
# **What does it impact**: Application stability.

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # for technote-space/get-diff-action to get git reference
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            **/go.mod
            **/go.sum
      - name: docker-test
        run: make e2e
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - name: docker-logs
        run: docker-compose ps
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - name: docker-logs-db
        run: docker-compose logs db
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - name: docker-logs-chora
        run: docker-compose logs chora
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - name: docker-logs-idx
        run: docker-compose logs idx
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - name: docker-logs-tester
        run: docker-compose logs tester
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'

  unit:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # for technote-space/get-diff-action to get git reference
    strategy:
      matrix:
        module: ["api", "db", "idx"]
    steps:
      - uses: actions/checkout@v4

      # api module

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            api/**/**.go
            api/go.mod
            api/go.sum
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'api/go.mod'
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - run: make test-api
        if: |
          (env.GIT_DIFF && matrix.module == 'api') ||
          github.ref == 'refs/heads/main'
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-api
          path: coverage-api.out
        if: |
          (env.GIT_DIFF && matrix.module == 'api') ||
          github.ref == 'refs/heads/main'

      # db module

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            db/**/**.go
            db/go.mod
            db/go.sum
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'db/go.mod'
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - run: make test-db
        if: |
          (env.GIT_DIFF && matrix.module == 'db') ||
          github.ref == 'refs/heads/main'
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-db
          path: coverage-db.out
        if: |
          (env.GIT_DIFF && matrix.module == 'db') ||
          github.ref == 'refs/heads/main'

      # idx module

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            idx/**/**.go
            idx/go.mod
            idx/go.sum
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'idx/go.mod'
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - run: make test-idx
        if: |
          (env.GIT_DIFF && matrix.module == 'idx') ||
          github.ref == 'refs/heads/main'
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-idx
          path: coverage-idx.out
        if: |
          (env.GIT_DIFF && matrix.module == 'idx') ||
          github.ref == 'refs/heads/main'

  coverage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # for technote-space/get-diff-action to get git reference
    needs: [unit]
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            **/go.mod
            **/go.sum
      - uses: actions/download-artifact@v4
        with:
          name: coverage-api
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - run: make test-coverage
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - uses: codecov/codecov-action@v4
        with:
          file: coverage.txt
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
